### ISSUE TITLE
BUG: Visual editor in WP 3.9.1 broken with advertizing manager enabled

### ISSUE THREAD

**Issue by lemmy04** [advertising-manager/advertising-manager-wordpress#11]
Since last night's update for advertizing manager, the visual editor component in WP 3.9.1 stopped working. The toolbar buttons won't load, and you can't type in the editor itself. Editing in "plaintext" html works.

**Comment by switzer** [comment]
Thanks for the report.  Do you get the ad icon in the visual editor (tinyMCE)?  Like below:

![image](https://cloud.githubusercontent.com/assets/201081/3626818/4612a27a-0e82-11e4-83e8-146da5730c92.png)

It could be an environment issue.  What other plugins are you running?  Also, do you know what version of PHP you are running?

Thanks

**Comment by lemmy04** [comment]
I don't get /any/ icons in the visual editor, it simply does not load.
And when I disable the advertising manager plugin and leave everything
else untouched, the editor works again.

I'm running php 5.3 there.

Am 18.07.2014 15:50, schrieb Scott Switzer:

**Comment by switzer** [comment]
Hmm - I will load this version of PHP and see if this is the issue.  What
other plugins are you running?

Thanks

**Comment by switzer** [comment]
And also - the editor plugin is javascript, so it could be a browser issue.
 What version of web browser are you running?  Thanks for helping sort this
out.

**Comment by lemmy04** [comment]
Here's the list of plugins that I'm running:

_Akismet_
Settings
http://yuukieonmura.eregion.de/wp-admin/options-general.php?page=akismet-key-config
| Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=akismet%2Fakismet.php&plugin_status=all&paged=1&s&_wpnonce=c096442a03
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=akismet/akismet.php

Used by millions, Akismet is quite possibly the best way in the world to
_protect your blog from comment and trackback spam_. It keeps your site
protected from spam even while you sleep. To get started: 1) Click the
"Activate" link to the left of this description, 2) Sign up for an
Akismet API key http://akismet.com/get/, and 3) Go to your Akismet
configuration page, and save your API key.

Version 3.0.1 | By Automattic http://automattic.com/wordpress-plugins/
| Visit plugin site http://akismet.com/
Select Google Analytics for WordPress   _Google Analytics for WordPress_
Settings
http://yuukieonmura.eregion.de/wp-admin/options-general.php?page=google-analytics-for-wordpress
| Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=google-analytics-for-wordpress%2Fgoogleanalytics.php&plugin_status=all&paged=1&s&_wpnonce=cb0cdb3667
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=google-analytics-for-wordpress/googleanalytics.php

This plugin makes it simple to add Google Analytics to your WordPress
blog, adding lots of features, eg. custom variables and automatic
clickout and download tracking.

Version 4.3.5 | By Joost de Valk http://yoast.com/ | Visit plugin site
http://yoast.com/wordpress/google-analytics/#utm_source=wordpress&utm_medium=plugin&utm_campaign=wpgaplugin&utm_content=v420
Select Mail From    _Mail From_
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=mail-from%2Fmail-from.php&plugin_status=all&paged=1&s&_wpnonce=1608b44d3f
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=mail-from/mail-from.php

Change the default address that WordPress sends it's email from.

Version 1.0.1 | By Andrew Hamilton http://andrewhamilton.net/ | Visit
plugin site http://code.andrewhamilton.net/wordpress/plugins/mail-from/
Select Meta Tag Manager     _Meta Tag Manager_
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=meta-tag-manager%2Fmeta-tag-manager.php&plugin_status=all&paged=1&s&_wpnonce=6efccfe525
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=meta-tag-manager/meta-tag-manager.php

A simple plugin to manage meta tags that appear on all your pages. This
can be used for verifiying google, yahoo, and more.

Version 1.2 | By NetWebLogic LLC http://netweblogic.com/ | Visit
plugin site http://netweblogic.com/wordpress/plugins/meta-tag-manager/
Select NextScripts: Social Networks Auto-Poster     _NextScripts: Social
Networks Auto-Poster_
Settings
http://yuukieonmura.eregion.de/wp-admin/options-general.php?page=NextScripts_SNAP.php
| Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=social-networks-auto-poster-facebook-twitter-g%2FNextScripts_SNAP.php&plugin_status=all&paged=1&s&_wpnonce=b69e27f389
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=social-networks-auto-poster-facebook-twitter-g/NextScripts_SNAP.php

This plugin automatically publishes posts from your blog to multiple
accounts on Facebook, Twitter, and Google+ profiles and/or pages.

Version 3.4.1 | By Next Scripts http://www.nextscripts.com | Visit
plugin site
http://www.nextscripts.com/social-networks-auto-poster-for-wordpress
Select Parent Category Toggler  _Parent Category Toggler_
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=parent-category-toggler%2Fparent-category-toggler.php&plugin_status=all&paged=1&s&_wpnonce=36c7b2d261
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=parent-category-toggler/parent-category-toggler.php

Automatically toggle the parent categories when a sub category is selected.

Version 1.3.1 | By Ben Lobaugh http://ben.lobaugh.net | Visit plugin
site http://wordpress.org/extend/plugins/parent-category-toggler/
Select Shareaholic | share buttons, analytics, related posts
_Shareaholic | share buttons, analytics, related posts_
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=sexybookmarks%2Fshareaholic.php&plugin_status=all&paged=1&s&_wpnonce=690941306a
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=sexybookmarks/shareaholic.php
| Settings
http://yuukieonmura.eregion.de/wp-admin/admin.php?page=shareaholic.php

Whether you want to get people sharing, grow your fans, make money, or
know who's reading your content, Shareaholic will help you get it done.
See configuration panel
http://yuukieonmura.eregion.de/wp-admin/admin.php?page=shareaholic.php
for more settings.

Version 6.1.5.1 | By Shareaholic https://shareaholic.com | Visit
plugin site https://shareaholic.com/publishers/
Select SI CAPTCHA Anti-Spam     _SI CAPTCHA Anti-Spam_
Settings
http://yuukieonmura.eregion.de/wp-admin/plugins.php?page=si-captcha-for-wordpress/si-captcha.php
| Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=si-captcha-for-wordpress%2Fsi-captcha.php&plugin_status=all&paged=1&s&_wpnonce=c4f920b886
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=si-captcha-for-wordpress/si-captcha.php

Adds CAPTCHA anti-spam methods to WordPress forms for comments,
registration, lost password, login, or all. This prevents spam from
automated bots. WP, WPMU, and BuddyPress compatible. Settings
http://yuukieonmura.eregion.de/wp-admin/plugins.php?page=si-captcha-for-wordpress/si-captcha.php
| Donate
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KXJWLPPWZG83S

Version 2.7.7.4 | By Mike Challis
http://www.642weather.com/weather/scripts.php | Visit plugin site
http://www.642weather.com/weather/scripts-wordpress-captcha.php
Select Slickr Flickr    _Slickr Flickr_
Settings
http://yuukieonmura.eregion.de/wp-admin/admin.php?page=slickr-flickr |
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=slickr-flickr%2Fslickr-flickr.php&plugin_status=all&paged=1&s&_wpnonce=4f463f50f6
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=slickr-flickr/slickr-flickr.php

Displays photos from Flickr in slideshows and galleries

Version 2.0 | By Russell Jamieson http://www.russelljamieson.com |
Visit plugin site http://www.slickrflickr.com
Select TimThumb Vulnerability Scanner   _TimThumb Vulnerability Scanner_
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=timthumb-vulnerability-scanner%2Ftimthumb-vulnerability-scanner.php&plugin_status=all&paged=1&s&_wpnonce=eef71877ec
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=timthumb-vulnerability-scanner/timthumb-vulnerability-scanner.php

Keep your instances of Timthumb up to date and free from vulnerabilities
simply. Bonus - checks for obvious signs of compromised sites.

Version 1.53 | By Peter Butler http://codegarage.com/ | Visit plugin
site http://codegarage.com/blog/plugins/timthumb-vulnerability-scanner
Select W3 Total Cache   _W3 Total Cache_
Settings
http://yuukieonmura.eregion.de/wp-admin/admin.php?page=w3tc_general |
Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=w3-total-cache%2Fw3-total-cache.php&plugin_status=all&paged=1&s&_wpnonce=1abce16d92
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=w3-total-cache/w3-total-cache.php

The highest rated and most complete WordPress performance plugin.
Dramatically improve the speed and user experience of your site. Add
browser, page, object and database caching as well as minify and content
delivery network (CDN) to WordPress.

Version 0.9.4 | By Frederick Townes http://www.linkedin.com/in/w3edge
| Visit plugin site
http://www.w3-edge.com/wordpress-plugins/w3-total-cache/
Select WP Updates Notifier  _WP Updates Notifier_
Settings
http://yuukieonmura.eregion.de/wp-admin/options-general.php?page=wp-updates-notifier
| Deactivate
http://yuukieonmura.eregion.de/wp-admin/plugins.php?action=deactivate&plugin=wp-updates-notifier%2Fwp-updates-notifier.php&plugin_status=all&paged=1&s&_wpnonce=b9028fbfc5
| Edit
http://yuukieonmura.eregion.de/wp-admin/plugin-editor.php?file=wp-updates-notifier/wp-updates-notifier.php

Sends email to notify you if there are any updates for your WordPress
site. Can notify about core, plugin and theme updates.

Version 1.4.1 | By Scott Cariss http://l3rady.com/ | Visit plugin site
https://github.com/l3rady/wp-updates-notifier

Am 18.07.2014 16:56, schrieb Scott Switzer:

**Comment by switzer** [comment]
Thanks for that.  I went through and installed every plugin, enabled each,
and I still cannot find an issue.  If you could give me a few other items:
1.  When you have advertising manager enabled, go to the edit post screen
   where the visual editor is located, so that you can see the error.  Do any
   errors output to the Javascript console?  (e.g in Google Chrome, view >
   developer > javascript console).  If so, can you send me the error, and
   also the 'view source' of the webpage?
2.  If you don't see anything in #1 above, are you getting any errors in
   your PHP log file?

If you want to contact me directly (skype:  switzer), we can coordinate me
logging into your admin console, and I should be able to fix it pretty
quickly this way.

Thanks!

**Comment by lemmy04** [comment]
_facepalm_

Found it. I have adblock edge in my browser, and it blocked the javascript 
from advertizing manager due to its url.
You can close this bug, maybe put an entry in the FAQ for advertising manager 
that says "disable adblockers for any hosts that you have this installed on".

Cheers,
MH

Am Freitag, 18. Juli 2014, 10:49:53 schrieb Scott Switzer:

> Thanks for that.  I went through and installed every plugin, enabled each,
> and I still cannot find an issue.  If you could give me a few other items:
> 1.  When you have advertising manager enabled, go to the edit post screen
>    where the visual editor is located, so that you can see the error.  Do any
>    errors output to the Javascript console?  (e.g in Google Chrome, view >
>    developer > javascript console).  If so, can you send me the error, and
>    also the 'view source' of the webpage?
> 2.  If you don't see anything in #1 above, are you getting any errors in
>    your PHP log file?
> 
> If you want to contact me directly (skype:  switzer), we can coordinate me
> logging into your admin console, and I should be able to fix it pretty
> quickly this way.
> 
> Thanks!
>

**Comment by switzer** [comment]
Glad to see that you found it!  by the way - what URL was blocked?

**Comment by lemmy04** [comment]
Hi,

/(hostname)/wp-content/plugins/advertising-manager/scripts/advman-
editor.js/[1] and some others from a different plugin.

_/Am/_ Freitag, 18. Juli 2014, 11:42:29 schrieb Scott Switzer:

> Glad to see that you found it!  by the way - what URL was blocked?
>

**Comment by switzer** [comment]
I guess that is the downside to having a plugin named 'ADVERTISING-manager'
:(  Perhaps I will look into shortening to advman...  Cheers.
