### ISSUE TITLE
Error messages on pages/posts without tags

### ISSUE THREAD

**Issue by kvibber** [advertising-manager/advertising-manager-wordpress#12]
When using tags as criteria, if an Ad Manager widget appears on a page with no tags assigned, it will spit out a series of errors in lib/OX/Ad.php instead of just staying blank.

**Comment by kvibber** [comment]
--- advertising-manager/lib/OX/Ad.php.orig  2014-07-18 17:33:17.040032954 -0700
+++ advertising-manager/lib/OX/Ad.php   2014-07-18 17:37:15.042991218 -0700
@@ -164,8 +164,10 @@
            $tags = get_the_tags();
            $found = false;
-           foreach ($tags as $tag) {
-               if (in_array($tag->term_id, $tagFilter)) {
-                   $found = true;
-                   break;
-                        if(isset($tags) && is_array($tags)) {
-               foreach ($tags as $tag) {
-                   if (in_array($tag->term_id, $tagFilter)) {
-                       $found = true;
-                       break;
-                   }
              }
          }

**Comment by switzer** [comment]
Thanks for the report.  Fixed in commit 958689.  This will be deployed in the next release.
